# scanners/sqlmap.py

import os
import re
import csv
import json
import glob
import time
from typing import Tuple, Optional

from core.config import SCAN_OUTPUT_DIR
from models.schemas import SqlmapScanResult, SqlmapVulnerability, ScanType
from utils.command_runner import run_command

async def run_sqlmap(target: str, scan_type: ScanType, scan_id: str, update_progress: callable, command_increment: float, timestamp: str) -> Tuple[SqlmapScanResult, Optional[str]]:
    target_sanitized = re.sub(r'[^a-zA-Z0-9.-]', '_', target).strip('_')
    sqlmap_output_dir = os.path.join(SCAN_OUTPUT_DIR, f"sqlmap_{target_sanitized}")
    filtered_output_file = os.path.join(SCAN_OUTPUT_DIR, f"sqlmap_filtered_{target_sanitized}_{timestamp}.json")
    
    command = [
        "sqlmap", "-u", target, 
        "--crawl=3", "--forms", "--batch", 
        "--threads=10", "--time-sec=3", 
        "--risk=3", "--level=3", 
        "--tamper=between", "--flush-session",
        "--output-dir", sqlmap_output_dir
    ]
    
    await update_progress(f"Executing SQLMap", 0)
    print(f"Executing command: {' '.join(command)}")
    
    # Record start time so we only parse the CSV generated by THIS specific scan
    start_time = time.time()
    
    try:
        await run_command(command, capture_output=False)
        await update_progress("SQLMap command completed", command_increment)
        
        vulns = []
        
        # 1. Search in our custom output dir
        csv_files = glob.glob(os.path.join(sqlmap_output_dir, "**", "*.csv"), recursive=True)
        
        # 2. Search in the default local share (where SQLMap usually forces the CSV)
        default_dir = os.path.expanduser("~/.local/share/sqlmap/output/")
        if os.path.exists(default_dir):
            csv_files.extend(glob.glob(os.path.join(default_dir, "*.csv")))
            
        # 3. Filter for CSVs created/modified in the last few minutes
        recent_csvs = [f for f in csv_files if os.path.getmtime(f) >= start_time - 5]
        
        if recent_csvs:
            latest_csv = max(recent_csvs, key=os.path.getctime)
            print(f"Parsing SQLMap CSV: {latest_csv}")
            
            # Translate SQLMap acronyms into readable text
            tech_map = {
                'B': 'Boolean-based blind',
                'E': 'Error-based',
                'U': 'Union query-based',
                'S': 'Stacked queries',
                'T': 'Time-based blind',
                'Q': 'Inline queries'
            }
            
            with open(latest_csv, mode='r', encoding='utf-8', errors='ignore') as csv_file:
                reader = csv.DictReader(csv_file)
                for row in reader:
                    raw_techs = row.get('Technique(s)', '')
                    readable_techs = ", ".join([tech_map.get(char, char) for char in raw_techs]) if raw_techs else "Unknown"
                    
                    vulns.append(SqlmapVulnerability(
                        parameter=row.get('Parameter', 'Unknown'),
                        type=row.get('Place', 'Unknown'),          # Maps to Method (POST/GET)
                        title=readable_techs,                      # Maps to Technique names
                        payload=row.get('Target URL', target)      # Maps to URL
                    ))
        
        if vulns:
            with open(filtered_output_file, 'w', encoding='utf-8') as f_out:
                json.dump([v.model_dump() for v in vulns], f_out, indent=4)
                
            # Note: Returning None for AI file because the Executive Summary handles it globally
            return SqlmapScanResult(vulnerabilities=vulns), None
            
        return SqlmapScanResult(vulnerabilities=[]), None
        
    except Exception as e:
        print(f"Error running SQLMap: {e}")
        await update_progress(f"SQLMap failed: {str(e)}", command_increment)
        return SqlmapScanResult(), None